title: Nicholas Santantonio
email: ns722@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
 Quantitative geneticist and plant breeder. Interested in breeding methodology for optimizing genetic gain, increasing crop resiliency, and predicting plant response to stress. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: santantonioN
github_username:  nsantantonio

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: TestDir
  url: ./testdir/test.html
# - title: Research
#   url: ./research.html
# - title: R Protocols
#   url: ./Rmd%20Protocols/R%20Protocols.html